#!/bin/bash

######################################################################
##               Reconftw Set Up Script                             ##
#######################################################################
# To loginto a droplet use ==>> ssh -i myssh1 root@159.223.234.137
#  alias do3='ssh -i myssh1 root@159.223.234.137'" >> .bashrc

s=2                                  # Slows scritpt down so you can see whats going on

printf '\n============================================================\n'
printf '[+] Updating System\n'
printf '============================================================\n\n'
apt update -y
apt upgrade -y
sleep $s

apt install wget
apt install git

printf '\n============================================================\n'
printf '[+]  Upload standard .bash_aliases & upgrades to .bashrc. \n'
printf '============================================================\n\n'
sleep $s


# Back-up original .bashrc incase I Fuck it up
if [ ! -f ~/.bashrc.bak ]; then   #Check if bashrc.bak has already been copied. If yes then skip
    cp /root/.bashrc /root/.bashrc.bak          # bak Up bashrc incase I fuck it up

    # Upload my standard aliases file
    wget https://raw.githubusercontent.com/leighton-0/Aliases-Bashrc-Scripts-and-Functions/master/.bash_aliases

#     # Add pointer to new .bash_aliases
#     cat <<"EOF" >>.bashrc           # use heredoc to add multiple lines to .bashrc. the -
#     test insert
#     # allows indetation
#     # if [ -f ~/.bash_aliases ]; then
#     #     . ~/.bash_aliases
# EOF
#     fi
cat <<"EOF" >>.bashrc
if [ -f ~/.bash_aliases ]; then
. ~/.bash_aliases
fi
EOF
